/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object ComplexServiceStages extends Table[(Int, Int, String, String)]("complex_service_stages") {
  def stageId = column[Int]("stage_id", O.NotNull, O.AutoInc)
  def sequence = column[Int]("sequence", O.NotNull)
  def stageName = column[String]("stage_name", O.NotNull)
  def displayName = column[String]("display_name", O.NotNull)
  def * = stageId ~ sequence ~ stageName ~ displayName
  def withAutoInc = sequence ~ stageName ~ displayName returning stageId
  def pk = primaryKey("complex_service_stages_pkey", (stageId))
  def complexServiceStagesPkey = index("complex_service_stages_pkey", (stageId), unique = true)
}
