/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object ComplexServiceContents extends Table[(Long, Int, Long, Int)]("complex_service_contents") {
  def complexServiceId = column[Long]("complex_service_id", O.NotNull)
  def stageId = column[Int]("stage_id", O.NotNull)
  def serviceId = column[Long]("service_id", O.NotNull)
  def sequence = column[Int]("sequence", O.NotNull)
  def * = complexServiceId ~ stageId ~ serviceId ~ sequence
  def pk = primaryKey("complex_service_contents_pkey", (complexServiceId, stageId, serviceId, sequence))
  def fkComplexServiceContentsComplexServiceStages = foreignKey("fk_complex_service_contents_complex_service_stages", (stageId), ComplexServiceStages)(t => (t.stageId))
  def fkComplexServiceContentsComplexServices = foreignKey("fk_complex_service_contents_complex_services", (complexServiceId), ComplexServices)(t => (t.serviceId))
  def fkComplexServiceContentsServices = foreignKey("fk_complex_service_contents_services", (serviceId), Services)(t => (t.serviceId))
  def idxServiceQuantitiesServices = index("idx_service_quantities_services", (serviceId))
  def idxServiceQuantitiesComplexServices = index("idx_service_quantities_complex_services", (complexServiceId))
  def complexServiceContentsPkey = index("complex_service_contents_pkey", (complexServiceId, stageId, serviceId, sequence), unique = true)
  def idxComplexServiceContentsComplexServices = index("idx_complex_service_contents_complex_services", (complexServiceId))
  def idxComplexServiceContentsServices = index("idx_complex_service_contents_services", (serviceId))
  def idxComplexServiceContentsComplexServiceStages = index("idx_complex_service_contents_complex_service_stages", (stageId))
}
