/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Organizations extends Table[(Long, String, String, String, String, String, String, String, String, Long, Long, Int, String, Int, Long, Long, String)]("organizations") {
  def contactId = column[Long]("contact_id", O.NotNull, O.AutoInc)
  def title = column[String]("title", O.NotNull)
  def ceoName = column[String]("ceo_name")
  def phone = column[String]("phone", O.NotNull)
  def fax = column[String]("fax")
  def website = column[String]("website")
  def email = column[String]("email")
  def registrationAddress = column[String]("registration_address", O.NotNull)
  def postalAddress = column[String]("postal_address")
  def ogrn = column[Long]("ogrn")
  def inn = column[Long]("inn", O.NotNull)
  def kpp = column[Int]("kpp", O.NotNull)
  def bankName = column[String]("bank_name", O.NotNull)
  def bik = column[Int]("bik", O.NotNull)
  def correspondentAccount = column[Long]("correspondent_account", O.NotNull)
  def settlementAccount = column[Long]("settlement_account", O.NotNull)
  def misc = column[String]("misc")
  def * = contactId ~ title ~ ceoName ~ phone ~ fax ~ website ~ email ~ registrationAddress ~ postalAddress ~ ogrn ~ inn ~ kpp ~ bankName ~ bik ~ correspondentAccount ~ settlementAccount ~ misc
  def idxOrganizationsContacts = index("idx_organizations_contacts", (contactId))
}
