/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Persons extends Table[(Long, String, Option[String], Option[String], Option[String], Long, Option[Long], Option[String], Option[String], Option[String], Option[Int], Option[String], Option[Double], Option[String])]("persons") {
  def contactId = column[Long]("contact_id", O.NotNull)
  def firstName = column[String]("first_name", O.NotNull)
  def middleName = column[Option[String]]("middle_name", O.Nullable)
  def lastName = column[Option[String]]("last_name", O.Nullable)
  def position = column[Option[String]]("position", O.Nullable)
  def cellPhone = column[Long]("cell_phone", O.NotNull)
  def fixedPhone = column[Option[Long]]("fixed_phone", O.Nullable)
  def passport = column[Option[String]]("passport", O.Nullable)
  def address = column[Option[String]]("address", O.Nullable)
  def district = column[Option[String]]("district", O.Nullable)
  def age = column[Option[Int]]("age", O.Nullable)
  def profession = column[Option[String]]("profession", O.Nullable)
  def averagePayment = column[Option[Double]]("average_payment", O.Nullable)
  def misc = column[Option[String]]("misc", O.Nullable)
  def * = contactId ~ firstName ~ middleName ~ lastName ~ position ~ cellPhone ~ fixedPhone ~ passport ~ address ~ district ~ age ~ profession ~ averagePayment ~ misc
  def pk = primaryKey("persons_pkey", (cellPhone))
  def fkPersonsContacts = foreignKey("fk_persons_contacts", (contactId), Contacts)(t => (t.contactId))
  def idxPersonsContacts = index("idx_persons_contacts", (contactId))
  def personsPkey = index("persons_pkey", (cellPhone), unique = true)
}
