/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Persons extends Table[(Long, String, String, String, String, Long, Long, String, String, String, Int, String, Int, String)]("persons") {
  def contactId = column[Long]("contact_id", O.NotNull, O.AutoInc)
  def firstName = column[String]("first_name", O.NotNull)
  def middleName = column[String]("middle_name")
  def lastName = column[String]("last_name")
  def position = column[String]("position")
  def cellPhone = column[Long]("cell_phone", O.NotNull)
  def fixedPhone = column[Long]("fixed_phone")
  def passport = column[String]("passport")
  def address = column[String]("address", O.NotNull)
  def district = column[String]("district")
  def age = column[Int]("age")
  def profession = column[String]("profession")
  def averagePayment = column[Int]("average_payment")
  def misc = column[String]("misc")
  def * = contactId ~ firstName ~ middleName ~ lastName ~ position ~ cellPhone ~ fixedPhone ~ passport ~ address ~ district ~ age ~ profession ~ averagePayment ~ misc
  def fkPersonsContacts = foreignKey("fk_persons_contacts", (contactId), Contacts)(t => (t.contactId))
  def idxPersonsContacts = index("idx_persons_contacts", (contactId))
  def personsPkey = index("persons_pkey", (contactId), unique = true)
}
