/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Requests extends Table[(Long, Long, Long, Long)]("requests") {
  def requestId = column[Long]("request_id", O.NotNull, O.AutoInc)
  def clientId = column[Long]("client_id", O.NotNull)
  def executorId = column[Long]("executor_id", O.NotNull)
  def taskId = column[Long]("task_id", O.NotNull)
  def * = requestId ~ clientId ~ executorId ~ taskId
  def withAutoInc = clientId ~ executorId ~ taskId returning requestId
  def pk = primaryKey("requests_pkey", (requestId))
  def fkRequestsClients = foreignKey("fk_requests_clients", (clientId), Contacts)(t => (t.contactId))
  def fkRequestsTasks = foreignKey("fk_requests_tasks", (taskId), Tasks)(t => (t.taskId))
  def fkRequestsExecutors = foreignKey("fk_requests_executors", (executorId), Contacts)(t => (t.contactId))
  def idxRequestsExecutors = index("idx_requests_executors", (executorId))
  def idxRequestsTasks = index("idx_requests_tasks", (taskId))
  def requestsPkey = index("requests_pkey", (requestId), unique = true)
  def idxRequestsClients = index("idx_requests_clients", (clientId))
}
