/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Roles extends Table[(Int, String, String)]("roles") {
  def roleId = column[Int]("role_id", O.NotNull, O.AutoInc)
  def roleName = column[String]("role_name", O.NotNull)
  def displayName = column[String]("display_name")
  def * = roleId ~ roleName ~ displayName
  def fkUserRolesRoles = foreignKey("fk_user_roles_roles", (roleId), UserRoles)(t => (t.roleId))
  def rolesPkey = index("roles_pkey", (roleId), unique = true)
}
