/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object ServiceQuantities extends Table[(Long, Long, Double)]("service_quantities") {
  def complexServiceId = column[Long]("complex_service_id", O.NotNull)
  def serviceId = column[Long]("service_id", O.NotNull)
  def quantity = column[Double]("quantity", O.NotNull)
  def * = complexServiceId ~ serviceId ~ quantity
  def pk = primaryKey("service_quantities_pkey", (complexServiceId, serviceId))
  def fkServiceQuantitiesServices = foreignKey("fk_service_quantities_services", (serviceId), Services)(t => (t.serviceId))
  def fkServiceQuantitiesComplexServices = foreignKey("fk_service_quantities_complex_services", (complexServiceId), ComplexServices)(t => (t.serviceId))
  def serviceQuantitiesPkey = index("service_quantities_pkey", (complexServiceId, serviceId), unique = true)
}
