/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Services extends Table[(Long, String, String, Double, Int)]("services") {
  def serviceId = column[Long]("service_id", O.NotNull, O.AutoInc)
  def serviceName = column[String]("service_name", O.NotNull)
  def unit = column[String]("unit", O.NotNull)
  def price = column[Double]("price", O.NotNull)
  def groupId = column[Int]("group_id")
  def * = serviceId ~ serviceName ~ unit ~ price ~ groupId
  def fkTaskServicesServices = foreignKey("fk_task_services_services", (serviceId), TaskServices)(t => (t.serviceId))
  def servicesPkey = index("services_pkey", (serviceId), unique = true)
  def idxServiceServiceGroups = index("idx_service_service_groups", (groupId))
}
