/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object ServiceGroups extends Table[(Int, String, Int)]("service_groups") {
  def groupId = column[Int]("group_id", O.NotNull, O.AutoInc)
  def groupName = column[String]("group_name", O.NotNull)
  def sequence = column[Int]("sequence", O.NotNull)
  def * = groupId ~ groupName ~ sequence
  def fkServicesServiceGroups = foreignKey("fk_services_service_groups", (groupId), Services)(t => (t.groupId))
  def serviceGroupsPkey = index("service_groups_pkey", (groupId), unique = true)
}
