/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object StoredCalculations extends Table[(Long, String, String)]("stored_calculations") {
  def storedCalculationId = column[Long]("stored_calculation_id", O.NotNull, O.AutoInc)
  def displayName = column[String]("display_name", O.NotNull)
  def data = column[String]("data", O.NotNull)
  def * = storedCalculationId ~ displayName ~ data
  def withAutoInc = displayName ~ data returning storedCalculationId
  def pk = primaryKey("stored_calculations_pkey", (storedCalculationId))
  def storedCalculationsPkey = index("stored_calculations_pkey", (storedCalculationId), unique = true)
}
