/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object TaskCategories extends Table[(Int, String, String)]("task_categories") {
  def categoryId = column[Int]("category_id", O.NotNull, O.AutoInc)
  def categoryName = column[String]("category_name", O.NotNull)
  def icon = column[String]("icon")
  def * = categoryId ~ categoryName ~ icon
  def fkTaskTemplatesTaskCategories = foreignKey("fk_task_templates_task_categories", (categoryId), TaskTemplates)(t => (t.categoryId))
  def fkTasksTaskCategories = foreignKey("fk_tasks_task_categories", (categoryId), Tasks)(t => (t.categoryId))
  def taskCategoriesPkey = index("task_categories_pkey", (categoryId), unique = true)
}
