/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object TaskStatuses extends Table[(Int, String, String)]("task_statuses") {
  def statusId = column[Int]("status_id", O.NotNull, O.AutoInc)
  def statusName = column[String]("status_name", O.NotNull)
  def icon = column[String]("icon")
  def * = statusId ~ statusName ~ icon
  def fkTaskTemplatesTaskStatuses = foreignKey("fk_task_templates_task_statuses", (statusId), TaskTemplates)(t => (t.statusId))
  def fkTasksTaskStatuses = foreignKey("fk_tasks_task_statuses", (statusId), Tasks)(t => (t.statusId))
  def taskStatusesPkey = index("task_statuses_pkey", (statusId), unique = true)
}
