/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/
package ru.meridor.diana.db.tables

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object TaskStatuses extends Table[(Int, String, Option[String])]("task_statuses") {
  def statusId = column[Int]("status_id", O.NotNull, O.AutoInc)
  def statusName = column[String]("status_name", O.NotNull)
  def icon = column[Option[String]]("icon", O.Nullable)
  def * = statusId ~ statusName ~ icon
  def withAutoInc = statusName ~ icon returning statusId
  def pk = primaryKey("task_statuses_pkey", (statusId))
  def taskStatusesPkey = index("task_statuses_pkey", (statusId), unique = true)
}
