/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object TaskPriorities extends Table[(Int, String, String)]("task_priorities") {
  def priorityId = column[Int]("priority_id", O.NotNull, O.AutoInc)
  def priorityName = column[String]("priority_name", O.NotNull)
  def icon = column[String]("icon")
  def * = priorityId ~ priorityName ~ icon
  def fkTasksTaskPriorities = foreignKey("fk_tasks_task_priorities", (priorityId), Tasks)(t => (t.priorityId))
  def fkTaskTemplatesTaskPriorities = foreignKey("fk_task_templates_task_priorities", (priorityId), TaskTemplates)(t => (t.priorityId))
  def taskPrioritiesPkey = index("task_priorities_pkey", (priorityId), unique = true)
}
