/***********************************************************
 * DO NOT EDIT THIS FILE - IT WAS GENERATED AUTOMATICALLY. *
 ***********************************************************/

import scala.slick.driver.PostgresDriver.simple._
import java.sql.Timestamp

object Users extends Table[(Int, String, String, Long)]("users") {
  def userId = column[Int]("user_id", O.NotNull, O.AutoInc)
  def email = column[String]("email", O.NotNull)
  def password = column[String]("password", O.NotNull)
  def contactId = column[Long]("contact_id")
  def * = userId ~ email ~ password ~ contactId
  def fkUserRolesUsers = foreignKey("fk_user_roles_users", (userId), UserRoles)(t => (t.userId))
  def usersPkey = index("users_pkey", (userId), unique = true)
  def usersEmailKey = index("users_email_key", (email), unique = true)
  def idxUsersContacts = index("idx_users_contacts", (contactId))
}
